name: krishi_unnati
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.2.3
  file_picker: ^10.3.3
  flutter_litert: ^3.1.2
  image: ^4.1.7

  # Map
  flutter_map: ^8.2.1
  latlong2: ^0.9.1

    # Farmer GPS location
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  cupertino_icons: ^1.0.8
  sms_autofill: ^2.5.0
  google_fonts: ^8.2.1

  shared_preferences: ^2.3.3
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0

  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/pest_model/pest_model_float32.tflite
    - assets/pest_model/labels.txt
  uses-material-design: true
